### ISSUE TITLE
ZF3 Compatibility and Zend\Mvc\Router\Http\Segment

### ISSUE THREAD

**Issue by misterpatate** [reliv/zf2-elfinder#25]
In the **module.config.php** file there are some routes with _Zend\Mvc\Router\Http\Segment_ type.
In ZF3, the Segment class no longer exist in the MVC module, it was moved to Router module, it's _\Zend\Router\Http\Segment_ now.

But if we replace **'Zend\Mvc\Router\Http\Segment'** by **\Zend\Router\Http\Segment::class** we break compatibility with ZF2.

Maybe it would be interesting to create a zf3-elfinder module ?

**Comment by misterpatate** [comment]
Additionally the **IndexControllerFactory** is broken due to change in FactoryInterface in ZF3.
`Class Reliv\ElFinder\Controller\IndexControllerFactory contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Zend\ServiceManager\Factory\FactoryInterface::__invoke)`

**Comment by rodmcnew** [comment]
Although this is Reliv's most popular OS project, we haven't used el-finder ourselves in years due to a switch to AWS S3. I'm happy to pull any PRs that I can easily see don't break anything but don't have much time to put toward this project.

If you want a ZF3 version, you may be best off forking this and publishing a zf3-elfinder version yourself.

@wshafer created this project. @wshafer - are you still using/maintaining zf2-elfinder?

**Comment by rodmcnew** [comment]
Also, if you or @wshafer wind up publishing your own ZF3 version. We could put a note on the readme for this one that we recommend yours for ZF3.

**Comment by wshafer** [comment]
I say we BC break the module and update it for ZF3.   @misterpatate I was porting this module over to expressive and I'd be happy to update this module at the same time.   I'm currently in the middle of working on the AssetManager library and this one was next my list.  I have no ETA when I get to it, but I don't think @rodmcnew would turn down the PR if you put one in.

@rodmcnew - I'm happy to maintain this library if you'd like to make me a collaborator on this repo.

**Comment by rodmcnew** [comment]
I cannot give any non-reliv-employees write-access to a repo that is in the "reliv" github organization.

Things I can do:

- Pull a BC breaking PR and tag it as a new major version
- Deprecate this module and forward its traffic to another organization or person.

Some thoughts though:
Even if @wshafer makes an expressive module version of this, expressive modules are not the same as ZF3 modules. Unless he plans on making a package that is both module types. Also "ZF2" is in the name of this package. Because of that, @jerv13 and I recommend just forking it. We could put a link to the fork in the readme for this one.

**Comment by wshafer** [comment]
No worries @rodmcnew, I can just create a new package for this.  And you're right ZF3 is not Expressive, I'll get er figured out.

**Comment by rodmcnew** [comment]
Sounds good. Yeah that part is tricky. I solved the same problem in https://github.com/reliv/zf-config-factories by providing both types of module files. Not sure if its an ideal solution though.

**Comment by wshafer** [comment]
Well ZF2 should be going away.  The upgrade from ZF2 to ZF3 was pretty trivial and the ZF crew are already moving away from ZF2 so a version bump an all the ZF2 modules and conversion to ZF3 I think is fine for most packages.

Getting this particular one going is a bit tougher because it's got a dependency on the Asset Manager, which I am currently in the middle of updating for ZF3 and Expressive.  Until that one gets done, I'll won't be able to shift this one.

That reminds me.  @rodmcnew I know you guys aren't really using it anymore, but I could use a second set of eyes on my PR's if you wouldn't mind giving me a hand maintaining that package.  Wess is no longer doing anything in PHP and has handed me the project.   But I'd still love a second pare of eyes on any PR's I submit for it.    Would you mind giving me a hand on that guy?

**Comment by wshafer** [comment]
NM I forgot, we no longer need AM to merge the JS and CSS.   So I can start shifting this one right away. :P

**Comment by rodmcnew** [comment]
Yes and the ZF3 module system and MVC system could die completely as even Zend's website now says they cannot think of any reason to use ZF-MVC over Expressive. And Expressive 2 has an official module system now rather than the "mostly official" one of v1.

Yeah we have pretty much abandoned the asset manager in favor of Webpack. We think that client packages should be handled the client way (Webpack is industry standard currently) and not by PHP. Its hard for me to engage with that project because I honestly don't think the asset manager should even exist. I think client packaging should happen at build time not runtime. (webpack style).

The simple and low-dependancy way we deal with a packages like el-finder is to webpack everything into a single js and css file, then use a simple middleware/controller to deliver them.

**Comment by wshafer** [comment]
Well we'll have to agree to disagree on the AM...  I'm not a fan of webpack at all and IMO just makes life more difficult for with little benefit.   Plus I don't like having to ask people to install a node stack and have a build process, just so they can use a package on a low volume site.  Also with HTTP2 and mobile, massive single js and css files are no longer considered "best practice" and files are once again getting split up and made smaller.  So with the exception of Babble and ReactJs that makes webpack even less worthwhile...  IMO.

But point taken, I'll find some other eyes to keep an eye on AM with me.  And I'll let you know when the ZF3 version of el-finder is up. ;)

**Comment by rodmcnew** [comment]
Since webpack is part of the build process its not needed by installers of the module (unlike asset manager). The module can come pre-built. But yes with http2, packing is not required anymore. It just makes it easier to deliver assets through single controller. Users of the module get simple pre-packed assets rather than a giant asset-management dependency to have to install. This makes the module much more lightweight and un-opinionated. To each their own though.

Ok. Sounds good.

**Comment by wshafer** [comment]
As Obi-Wan would say, "I once thought like you do."  In fact I went looking for other asset solutions myself.  I even saw your middleware layer too.    Like yours they either always served static files from PHP (which is not good imo), or required some composer plugin with some end user configuration to their app composer file to insure the files get copied correctly.   None of them worked out of the box nor allowed for generic caching of assets that could make a majority of users happy.   And unlike CakePhp or Symfony we have no native solution for assets in Zend.    That's why I went back to the AM + Assetic.

**Comment by rodmcnew** [comment]
@wshafer 

You're last comment showed up in my email but not on here. Yes I agree there is no perfect solution for static assets in PHP packages. I would favor portability over caching and choose delivering with built-in controllers/middleware. But I also totally understand people who want to favor caching over portability.

**Comment by wshafer** [comment]
Yea I deleted it.  Sometimes I argue I think just to hear myself argue or get the last word.  Realized it wasn't constructive and removed it.  :D

**Comment by rodmcnew** [comment]
Ah no worries. I thought it had legitimate points. Me and @jerv13 have had all the same debates about assets. I think the core of it is the age old "low dependencies" vs "don't copy and paste". I've been on a low dependencies kick lately so I've been arguing that side alot. But really both sides are valid.

**Comment by koseduhemak** [comment]
just added zf3 compatibility via pull request @27.
Maybe you can introduce a new branch 3.x so we can keep zf2 compatibility in the 2.x branch.

**Comment by rodmcnew** [comment]
zf2-elfinder version 3.0.0 solves this issue and adds ZF3 compatibility.
